# Generated by Django 3.2.4 on 2021-07-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='link',
            field=models.CharField(default=1, max_length=64, unique=True, verbose_name='ссылка'),
            preserve_default=False,
        ),
    ]
